kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: private-cluster-rhapi-apischeme-updater
subjects:
- kind: ServiceAccount
  name: private-cluster-rhapi-apischeme-updater
  namespace: openshift-private-cluster-rhapi-apischeme-updater
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: private-cluster-rhapi-apischeme-updater