apiVersion: v1
kind: Template
parameters:
- name: REGISTRY_IMG
  required: true
- name: IMAGE_TAG
  required: true
- name: REPO_NAME
  value: REPLACED_BY_SCRIPT
  required: true
metadata:
  name: private-cluster-rhapi-apischeme-updater-template
objects: []